milk:
  model_type: urdf
  position.x: -2.95
  position.y: 0.0
  position.z: 1.02
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

jodsalz:
  model_type: model
  position.x: -2.95
  position.y: 0.1
  position.z: 1
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

tomaten_suppe:
  model_type: model
  position.x: -2.95
  position.y: -0.1
  position.z: 1
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

zwieback:
  model_type: model
  position.x: -2.95
  position.y: 0.2
  position.z: 1
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

kraeuter:
  model_type: model
  position.x: -2.95
  position.y: -0.2
  position.z: 1
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

cb_4x3:
  model_type: model
  position.x: -0.7
  position.y: -0.1
  position.z: 1
  orientation.r: 1.56
  orientation.p: 0
  orientation.y: 1.56

cb_9x6:
  model_type: model
  position.x: -0.7
  position.y: -0.1
  position.z: 1
  orientation.r: 1.56
  orientation.p: 0
  orientation.y: 1.56


table_ikea:
  model_type: urdf.xacro
  position.x: 1.1
  position.y: 1.2
  position.z: 0
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

bookcase:
  model_type: urdf.xacro
  position.x: -1.2
  position.y: -1.9
  position.z: 0
  orientation.r: 0
  orientation.p: 0
  orientation.y: -1.57079

chair:
  model_type: urdf.xacro
  position.x: 1.1
  position.y: 1.2
  position.z: 0.1
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

cabinet:
  model_type: urdf.xacro
  position.x: 1.159
  position.y: 1.416
  position.z: 0
  orientation.r: 0
  orientation.p: 0
  orientation.y: 0

cabinet_with_door:
  model_type: urdf.xacro
  position.x: 2.2
  position.y: -1.97
  position.z: 0
  orientation.r: 0
  orientation.p: 0
  orientation.y: -1.57079
