milk:
  model_type: urdf
  position.x: -2.95
  position.y: 0.0
  position.z: 1.02
  orientation.x: 0
  orientation.y: 0
  orientation.z: 0
  orientation.w: 0

jodsalz:
  model_type: model
  position.x: -2.95
  position.y: 0.1
  position.z: 1
  orientation.x: 0
  orientation.y: 0
  orientation.z: 0
  orientation.w: 0

tomaten_suppe:
  model_type: model
  position.x: -2.95
  position.y: -0.1
  position.z: 1
  orientation.x: 0
  orientation.y: 0
  orientation.z: 0
  orientation.w: 0

zwieback:
  model_type: model
  position.x: -2.95
  position.y: 0.2
  position.z: 1
  orientation.x: 0
  orientation.y: 0
  orientation.z: 0
  orientation.w: 0

kraeuter:
  model_type: model
  position.x: -2.95
  position.y: -0.2
  position.z: 1
  orientation.x: 0
  orientation.y: 0
  orientation.z: 0
  orientation.w: 0
